// Product controls only. Author-supplied titles, cards, code and paths stay unchanged.
const messages: Array<[string, string, string]> = [
  ['{count} files', 'Файлов: {count}', '{count} 个文件'],
  ['Releases and tags', 'Релизы и теги', '版本与标签'],
  ['Import progress', 'Ход импорта', '导入进度'],
  ['copies an exact revision into a draft. Preview and finish its page in Workspace before publishing.', 'копирует точную ревизию в черновик. Просмотрите и оформите страницу в рабочем пространстве перед публикацией.', '将精确修订复制到草稿。发布前，请在工作区预览并完善页面。'],
  ['Super ii copies the exact version, checks its files and records the source. Open the finished import in Workspace to edit its page and submit publication checks.', 'Super ii копирует точную версию, проверяет файлы и записывает источник. Откройте готовый импорт в рабочем пространстве, оформите страницу и отправьте её на проверки публикации.', 'Super ii 复制精确版本、检查文件并记录来源。导入完成后，在工作区编辑页面并提交发布检查。'],
  ['Files and page', 'Файлы и страница', '文件与页面'],
  ['Start with your work', 'Начните со своей работы', '从您的作品开始'],
  ['Published version', 'Опубликованная версия', '已发布版本'],
  ['Draft version', 'Черновик', '草稿版本'],
  ['Add files or a folder. We will suggest details from your README and configuration.', 'Добавьте файлы или папку. Мы предложим сведения из README и конфигурации.', '添加文件或文件夹。我们会根据 README 和配置提供建议。'],
  ['Already online? Bring my work →', 'Работа уже в сети? Перенести →', '作品已在线？导入我的作品 →'],
  ['Repository type', 'Тип репозитория', '仓库类型'],
  ['Log in to choose an owner', 'Войдите, чтобы выбрать владельца', '登录后选择所有者'],
  ['This published version stays unchanged while you prepare an update.', 'Опубликованная версия не изменится, пока вы готовите обновление.', '准备更新时，此已发布版本保持不变。'],
  ['This revision is sealed. Start an update to make changes.', 'Эта ревизия закрыта для изменений. Создайте обновление.', '此修订已锁定。请创建更新以进行修改。'],
  ['Edit this page', 'Редактировать страницу', '编辑此页面'],
  ['Files and folders', 'Файлы и папки', '文件和文件夹'],
  ['Drop files here', 'Перетащите файлы сюда', '将文件拖放到此处'],
  ['Up to 10 GiB per file. Use Choose folder to keep nested folders.', 'До 10 ГиБ на файл. «Выбрать папку» сохраняет вложенные папки.', '每个文件最大 10 GiB。使用“选择文件夹”保留子文件夹。'],
  ['Choose files', 'Выбрать файлы', '选择文件'],
  ['Choose folder', 'Выбрать папку', '选择文件夹'],
  ['Selected files', 'Выбранные файлы', '已选文件'],
  ['Checks', 'Проверки', '检查'],
  ['Scanned', 'Проверено', '已扫描'],
  ['Remove', 'Убрать', '移除'],
  ['Choose Edit this page to add, replace or remove files in a new draft.', 'Нажмите «Редактировать страницу», чтобы добавить, заменить или удалить файлы в новом черновике.', '选择“编辑此页面”，即可在新草稿中添加、替换或移除文件。'],
  ['Page details and preview', 'Сведения и предпросмотр', '页面详情与预览'],
  ['Make it yours', 'Оформите по-своему', '按您的想法呈现'],
  ['A clear name for your work', 'Понятное название работы', '为作品起一个清晰的名称'],
  ['Repository URL name', 'Имя репозитория в URL', '仓库网址名称'],
  ['Suggested from your title. You can change it before creating.', 'Предложено по названию. Можно изменить перед созданием.', '根据标题建议。创建前可以修改。'],
  ['What it does, who it helps, and important limitations.', 'Что делает работа, кому полезна и какие есть ограничения.', '介绍功能、适用人群及重要限制。'],
  ['License, task and framework', 'Лицензия, задача и фреймворк', '许可证、任务与框架'],
  ['Choose or type your license', 'Выберите или введите лицензию', '选择或输入许可证'],
  ['Change license in publication details', 'Изменить лицензию в сведениях о публикации', '在发布详情中更改许可证'],
  ['Library / framework', 'Библиотека / фреймворк', '库 / 框架'],
  ['README / model card', 'README / карточка модели', 'README / 模型卡片'],
  ['Use a starter template', 'Использовать шаблон', '使用入门模板'],
  ['Read a README', 'Загрузить README', '读取 README'],
  ['The README is your public card. Tables, code, links and uploaded images appear in the preview. Only include verification claims you can support.', 'README — публичная карточка работы. Предпросмотр показывает таблицы, код, ссылки и загруженные изображения. Указывайте только подтверждённые результаты проверок.', 'README 是作品的公开卡片。预览会显示表格、代码、链接和已上传图片。仅填写有证据支持的验证结论。'],
  ['Card formatting', 'Оформление карточки', '卡片格式'],
  ['Heading', 'Заголовок', '标题'],
  ['Bold', 'Жирный', '加粗'],
  ['Link', 'Ссылка', '链接'],
  ['Code', 'Код', '代码'],
  ['Table', 'Таблица', '表格'],
  ['Insert image', 'Вставить изображение', '插入图片'],
  ['Choose an uploaded image', 'Выберите загруженное изображение', '选择已上传的图片'],
  ['Write in Markdown', 'Текст в Markdown', '使用 Markdown 编写'],
  ['Page preview', 'Предпросмотр страницы', '页面预览'],
  ['Live preview', 'Предпросмотр', '实时预览'],
  ['Your page title', 'Название вашей страницы', '您的页面标题'],
  ['Raw HTML stays as text. External images are links; uploaded PNG, JPEG, WebP and GIF files can appear directly.', 'HTML отображается как текст. Внешние изображения остаются ссылками; загруженные PNG, JPEG, WebP и GIF можно показывать на странице.', '原始 HTML 显示为文本。外部图片显示为链接；已上传的 PNG、JPEG、WebP 和 GIF 可直接显示。'],
  ['Save draft', 'Сохранить черновик', '保存草稿'],
  ['Create draft and upload', 'Создать черновик и загрузить', '创建草稿并上传'],
  ['Pause after this file', 'Пауза после этого файла', '完成此文件后暂停'],
  ['Saving keeps your work in a draft. Publish when you are ready.', 'Сохранение оставляет работу в черновике. Опубликуйте её, когда будете готовы.', '保存后作品仍是草稿。准备好后再发布。'],
  ['Log in to continue', 'Войдите, чтобы продолжить', '登录以继续'],
  ['Upload progress', 'Ход загрузки', '上传进度'],
  ['Ready to publish?', 'Готово к публикации?', '准备好发布了吗？'],
  ['Draft readiness', 'Готовность черновика', '草稿准备情况'],
  ['Add at least one repository file.', 'Добавьте хотя бы один файл.', '请至少添加一个仓库文件。'],
  ['README / model card supplied.', 'README / карточка модели добавлены.', '已提供 README / 模型卡片。'],
  ['Add a README so visitors can understand and use your work.', 'Добавьте README, чтобы посетители могли понять и использовать работу.', '添加 README，帮助访客理解并使用您的作品。'],
  ['Choose a license in the publication details below.', 'Выберите лицензию в сведениях о публикации ниже.', '在下方发布详情中选择许可证。'],
  ['File checks are available.', 'Проверки файлов доступны.', '文件检查可用。'],
  ['File checks are temporarily unavailable. Your draft is preserved.', 'Проверки файлов временно недоступны. Черновик сохранён.', '文件检查暂时不可用。草稿已保留。'],
  ['Earlier checks', 'Предыдущие проверки', '之前的检查'],
  ['Branches and automation', 'Ветки и автоматизация', '分支与自动化'],
  ['Ready in Workspace', 'Готово в рабочем пространстве', '已就绪，可在工作区编辑'],
  ['Open in Workspace', 'Открыть в рабочем пространстве', '在工作区打开'],
  ['Ready to upload', 'Готово к загрузке', '等待上传'],
  ['Uploading and checking…', 'Загрузка и проверка…', '正在上传并检查…'],
  ['Uploaded · checks passed', 'Загружено · проверки пройдены', '已上传 · 检查通过'],
  ['Needs attention · retry to resume', 'Требуется внимание · повторите для продолжения', '需要处理 · 重试以继续'],
  ['Creating your draft…', 'Создаём черновик…', '正在创建草稿…'],
  ['Checking the current draft…', 'Проверяем текущий черновик…', '正在检查当前草稿…'],
  ['The draft changed in another tab. Reload it before uploading or saving.', 'Черновик изменён в другой вкладке. Обновите страницу перед загрузкой или сохранением.', '草稿已在其他标签页中更改。上传或保存前请重新加载。'],
  ['Could not save. Please retry.', 'Не удалось сохранить. Повторите попытку.', '无法保存。请重试。'],
  ['Could not save. Retry to resume.', 'Не удалось сохранить. Повторите, чтобы продолжить.', '无法保存。重试以继续。'],
  ['Remove {path}', 'Убрать {path}', '移除 {path}'],
  ['This README is larger than 100 KB. Shorten it before using it as your card.', 'README больше 100 КБ. Сократите его перед использованием в карточке.', 'README 超过 100 KB。请缩短后再用作卡片。'],
  ['Replace the current card with this README?', 'Заменить текущую карточку этим README?', '用此 README 替换当前卡片？'],
  ['{path}: choose a non-empty file up to 10 GiB.', '{path}: выберите непустой файл до 10 ГиБ.', '{path}：请选择不超过 10 GiB 的非空文件。'],
  ['{path} is already selected. Remove it before choosing a replacement.', '{path} уже выбран. Уберите его перед выбором замены.', '已选择 {path}。请选择移除后再替换。'],
  ['{count} files selected. Review suggested details before saving.', 'Выбрано файлов: {count}. Проверьте предложенные сведения перед сохранением.', '已选择 {count} 个文件。保存前请检查建议的详情。'],
  ['{count} system or invalid paths skipped.', 'Пропущено системных или недопустимых путей: {count}.', '已跳过 {count} 个系统文件或无效路径。'],
  ['Files could not be selected.', 'Не удалось выбрать файлы.', '无法选择文件。'],
  ['README could not be read.', 'Не удалось прочитать README.', '无法读取 README。'],
  ['Use Choose folder to preserve all nested files.', 'Используйте «Выбрать папку», чтобы сохранить вложенные файлы.', '请使用“选择文件夹”保留所有嵌套文件。'],
  ['Replace the current card with a starter template?', 'Заменить текущую карточку шаблоном?', '用入门模板替换当前卡片？'],
  ['The queue will pause after the current file finishes.', 'Очередь приостановится после текущего файла.', '当前文件完成后队列将暂停。'],
  ['Could not start an update.', 'Не удалось начать обновление.', '无法开始更新。'],
  ['Keep the model card within 100 KB.', 'Карточка должна быть не больше 100 КБ.', '模型卡片不能超过 100 KB。'],
  ['Paused. Save draft resumes the remaining files.', 'Пауза. «Сохранить черновик» продолжит загрузку оставшихся файлов.', '已暂停。选择“保存草稿”可继续上传剩余文件。'],
  ['Draft saved. Review the publication checks when you are ready.', 'Черновик сохранён. Проверьте условия публикации, когда будете готовы.', '草稿已保存。准备好后请查看发布检查。'],
  ['Save your draft before running publication checks.', 'Сохраните изменения страницы перед проверками публикации.', '运行发布检查前请保存页面修改。'],
  ['Hashing {name}… {percent}%', 'Вычисляем хеш {name}… {percent}%', '正在计算 {name} 的哈希… {percent}%'],
  ['Uploading {name}… {percent}%', 'Загружаем {name}… {percent}%', '正在上传 {name}… {percent}%'],
  ['Scanning {name} in quarantine… You can keep this tab open.', 'Проверяем {name} в карантине… Оставьте вкладку открытой.', '正在隔离区扫描 {name}… 请保持此标签页打开。'],
  ['Scanning {name} in quarantine…', 'Проверяем {name} в карантине…', '正在隔离区扫描 {name}…'],
];

export const creatorRussian = Object.fromEntries(messages.map(([en, ru]) => [en, ru]));
export const creatorChinese = Object.fromEntries(messages.map(([en, , zh]) => [en, zh]));
export function translateCreator(text: string, locale = 'en', values: Record<string, string | number> = {}): string {
  const translated = (locale === 'ru' ? creatorRussian[text] : locale === 'zh-CN' ? creatorChinese[text] : text) ?? text;
  return translated.replace(/\{(\w+)\}/g, (match, key) => String(values[key] ?? match));
}
