const standardErrors = {
  '422': { description: 'Strict input validation failed' },
  '429': { $ref: '#/components/responses/RateLimited' },
  '503': { $ref: '#/components/responses/Unavailable' },
};

export const robotApiPaths = {
  '/api/robot/components': { get: { tags: ['Robot'], operationId: 'searchRobotComponents', summary: 'Search source-backed Robot components without paid ranking', security: [], parameters: [
    { name: 'q', in: 'query', schema: { type: 'string', maxLength: 120 } }, { name: 'platform', in: 'query', schema: { type: 'string', enum: ['raspberry-pi','jetson'] } }, { name: 'category', in: 'query', schema: { type: 'string', enum: ['compute','vision','thermal','power','mobile-base'] } }, { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 50, default: 20 } },
  ], responses: { '200': { description: 'Real, possibly empty component result' }, ...standardErrors } } },
  '/api/robot/components/{slug}': { get: { tags: ['Robot'], operationId: 'getRobotComponent', summary: 'Read one component, evidence, sources and recorded compatibility claims', security: [], parameters: [{ name: 'slug', in: 'path', required: true, schema: { type: 'string', pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$' } }], responses: { '200': { description: 'Source-backed component profile' }, '404': { description: 'Component not found' } } } },
  '/api/robot/plan': { post: { tags: ['Robot'], operationId: 'makeRobotPlan', summary: 'Create a deterministic Rover One starting plan', description: 'Returns a parts list, evidence, open requirements and Robot Check. It is not a safety approval.', security: [], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/RobotPlannerInput' } } } }, responses: { '200': { description: 'Server-computed Robot plan' }, ...standardErrors } } },
  '/api/robot/robots': {
    get: { tags: ['Robot'], operationId: 'searchPublicRobots', summary: 'Search real published community Robots', security: [], parameters: [{ name: 'q', in: 'query', schema: { type: 'string', maxLength: 120 } }, { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 50 } }, { name: 'offset', in: 'query', schema: { type: 'integer', minimum: 0, maximum: 10000 } }], responses: { '200': { description: 'Real, possibly empty published Robot result' }, ...standardErrors } },
    post: { tags: ['Robot'], operationId: 'createRobot', summary: 'Save version 1 under the signed-in owner', description: 'Public personal Robots are Free. Private personal Robots require Pro. Organization Robots require Team or Enterprise.', security: [{ clerkSession: [] }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/RobotCreateInput' } } } }, responses: { '201': { description: 'Robot and immutable version created' }, '401': { $ref: '#/components/responses/Unauthorized' }, '403': { $ref: '#/components/responses/Forbidden' }, ...standardErrors } },
  },
  '/api/robot/robots/{owner}/{slug}': { get: { tags: ['Robot'], operationId: 'getPublicRobot', summary: 'Read one current published Robot version', security: [], parameters: [{ name: 'owner', in: 'path', required: true, schema: { type: 'string' } }, { name: 'slug', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'Published Robot document' }, '404': { description: 'Public Robot not found' }, '429': { $ref: '#/components/responses/RateLimited' }, '503': { $ref: '#/components/responses/Unavailable' } } } },
  '/api/robot/robots/{robotId}/versions': { post: { tags: ['Robot'], operationId: 'createRobotVersion', summary: 'Append an immutable server-computed Robot version', security: [{ clerkSession: [] }], parameters: [{ name: 'robotId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['change_summary','planner_input'], properties: { change_summary: { type: 'string', minLength: 1, maxLength: 1000 }, planner_input: { $ref: '#/components/schemas/RobotPlannerInput' } }, additionalProperties: false } } } }, responses: { '201': { description: 'Immutable version created' }, '401': { $ref: '#/components/responses/Unauthorized' }, '403': { $ref: '#/components/responses/Forbidden' }, ...standardErrors } } },
  '/api/robot/hardware': {
    get: { tags: ['Robot'], operationId: 'listMyRobotHardware', summary: 'List private personal and authorized organization hardware', security: [{ clerkSession: [] }], responses: { '200': { description: 'Private hardware inventory' }, '403': { description: 'Pro or eligible Team plan required' } } },
    post: { tags: ['Robot'], operationId: 'addMyRobotHardware', summary: 'Add a private hardware item', security: [{ clerkSession: [] }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/RobotHardwareInput' } } } }, responses: { '201': { description: 'Hardware saved' }, '403': { description: 'Pro or eligible Team plan required' }, ...standardErrors } },
  },
  '/api/robot/hardware/{hardwareId}': { delete: { tags: ['Robot'], operationId: 'archiveMyRobotHardware', summary: 'Archive an owned hardware item', security: [{ clerkSession: [] }], parameters: [{ name: 'hardwareId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], responses: { '200': { description: 'Hardware archived' }, '404': { description: 'Owned item not found' } } } },
  '/api/robot/components/{slug}/claims': { post: { tags: ['Robot'], operationId: 'proposeRobotComponentMaintenance', summary: 'Submit a source-backed manufacturer profile proposal for independent review', security: [{ clerkSession: [] }], parameters: [{ name: 'slug', in: 'path', required: true, schema: { type: 'string' } }], responses: { '201': { description: 'Pending proposal recorded; public profile unchanged' }, '403': { description: 'Eligible organization owner/admin required' }, ...standardErrors } } },
  '/api/robot/analytics': { get: { tags: ['Robot'], operationId: 'getRobotDiscoveryAnalytics', summary: 'Read anonymous agent-discovery aggregates for an approved maintained component', description: 'Available only to the eligible organization maintaining the component. Analytics never affect rank.', security: [{ clerkSession: [] }], parameters: [{ name: 'organization_id', in: 'query', required: true, schema: { type: 'string', format: 'uuid' } }, { name: 'component', in: 'query', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'Ninety-day anonymous aggregate' }, '403': { $ref: '#/components/responses/Forbidden' } } } },
  '/a2a/robot/v1/message:send': { post: { tags: ['A2A','Robot'], operationId: 'sendRobotA2AMessage', summary: 'Invoke one public read-only Robot skill over A2A v1.0', security: [], requestBody: { required: true, content: { 'application/a2a+json': { schema: { $ref: '#/components/schemas/A2ASendMessageRequest' } } } }, responses: { '200': { description: 'Immediate terminal A2A task' }, '400': { description: 'Invalid A2A request or version' }, '429': { $ref: '#/components/responses/RateLimited' }, '503': { $ref: '#/components/responses/Unavailable' } } } },
} as const;
export const robotOpenApiSchemas = {
  RobotPlannerInput: { type: 'object', required: ['goal','experience','compute','environment','budget'], properties: { goal: { type: 'string', enum: ['see','follow','explore','learn'] }, experience: { type: 'string', enum: ['new','experienced','professional'] }, compute: { type: 'string', enum: ['recommend','pi5','jetson'] }, environment: { type: 'string', enum: ['indoor','controlled-outdoor'] }, budget: { type: 'string', enum: ['under-500','500-1000','over-1000','not-sure'] }, owned_components: { type: 'array', maxItems: 30, items: { type: 'string' }, default: [] } }, additionalProperties: false },
  RobotCreateInput: { type: 'object', required: ['slug','title','summary','audience','visibility','planner_input'], properties: { slug: { type: 'string', maxLength: 96, pattern: '^[a-z0-9](?:[a-z0-9-]{0,94}[a-z0-9])?$' }, title: { type: 'string', minLength: 2, maxLength: 160 }, summary: { type: 'string', minLength: 10, maxLength: 2000 }, audience: { type: 'string', minLength: 1, maxLength: 160 }, visibility: { type: 'string', enum: ['public','private'] }, organization_id: { type: ['string','null'], format: 'uuid' }, change_summary: { type: 'string', minLength: 1, maxLength: 1000 }, planner_input: { $ref: '#/components/schemas/RobotPlannerInput' } }, additionalProperties: false },
  RobotHardwareInput: { type: 'object', properties: { component_slug: { type: ['string','null'] }, custom_name: { type: ['string','null'], maxLength: 160 }, quantity: { type: 'integer', minimum: 1, maximum: 10000 }, notes: { type: 'string', maxLength: 2000 }, status: { type: 'string', enum: ['available','in-use','repair','retired'] }, organization_id: { type: ['string','null'], format: 'uuid' } }, additionalProperties: false, description: 'Exactly one of component_slug and custom_name is required.' },
} as const;
