-- A new immutable revision may reuse clean object bytes, but it must never
-- inherit security-inspection rows from its parent. The runtime re-runs every
-- required inspection when the creator submits the revision. Besides keeping
-- the evidence revision-specific, this lets the least-privilege web role start
-- a commit without gaining authority to write scanner results.

begin;

create or replace function app.create_repository_commit(
  p_repository_id uuid,
  p_branch_id uuid,
  p_message text,
  p_created_by text
)
returns app.repository_revisions
language plpgsql
security invoker
set search_path = app, pg_catalog
as $$
declare
  target_branch app.repository_branches;
  created_revision app.repository_revisions;
begin
  select * into target_branch
  from app.repository_branches
  where id = p_branch_id and repository_id = p_repository_id
  for update;
  if not found then
    raise exception 'branch_not_found' using errcode = 'P0002';
  end if;
  if target_branch.head_revision_id is not null and exists (
    select 1 from app.repository_revisions
    where id = target_branch.head_revision_id
      and status in ('draft', 'quarantined', 'scanning')
  ) then
    raise exception 'branch_has_editable_revision' using errcode = 'P0001';
  end if;

  select * into created_revision
  from app.create_repository_revision(
    p_repository_id,
    target_branch.head_revision_id,
    left(coalesce(p_message, ''), 2000),
    p_created_by
  );

  update app.repository_revisions
  set branch_id = p_branch_id
  where id = created_revision.id;

  if target_branch.head_revision_id is not null then
    insert into app.repository_files (
      repository_id, revision_id, path, size_bytes, mime_type, sha256,
      storage_key, storage_state, scan_status, created_by
    )
    select
      repository_id, created_revision.id, path, size_bytes, mime_type, sha256,
      storage_key, storage_state, scan_status, p_created_by
    from app.repository_files
    where revision_id = target_branch.head_revision_id
      and storage_state = 'available' and scan_status = 'clean';

    -- Inspection results intentionally are not copied. They describe the
    -- parent revision and are regenerated by the runtime before publication.
    update app.repository_revisions
    set status = case when exists (
          select 1 from app.repository_files where revision_id = created_revision.id
        ) then 'quarantined'::public.repository_revision_status
        else 'draft'::public.repository_revision_status end,
        file_count = (select count(*) from app.repository_files where revision_id = created_revision.id),
        total_size_bytes = coalesce((
          select sum(size_bytes) from app.repository_files where revision_id = created_revision.id
        ), 0)
    where id = created_revision.id;
  end if;

  update app.repository_branches
  set head_revision_id = created_revision.id, updated_at = now()
  where id = p_branch_id;

  select * into created_revision from app.repository_revisions where id = created_revision.id;
  return created_revision;
end;
$$;

comment on function app.create_repository_commit(uuid,uuid,text,text) is
  'Starts an immutable revision by reusing clean object bytes; inspection evidence is regenerated on submit';

commit;
